In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[455, 9752, 5327, 3027],
 [455, 9752, 5327, 3962],
 [455, 2836, 5327, 1612],
 [4392, 6328, 2661, 6068, 7272],
 [4392, 6328, 2661, 6068, 2448],
 [8014, 455, 5929, 5327, 2294],
 [1024, 9291, 6384, 6068]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  455 9752 5327 3027]
 [   0    0    0    0  455 9752 5327 3962]
 [   0    0    0    0  455 2836 5327 1612]
 [   0    0    0 4392 6328 2661 6068 7272]
 [   0    0    0 4392 6328 2661 6068 2448]
 [   0    0    0 8014  455 5929 5327 2294]
 [   0    0    0    0 1024 9291 6384 6068]]


In [10]:
## feature representation
dim=10

In [19]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

d:\Swapil2\LEARNING\Udemy-Krish\ANN\ANN_Classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 208ms/step


array([[[ 1.58396028e-02, -1.56264789e-02, -8.79174471e-03,
         -4.13482413e-02,  4.69103567e-02,  4.63138893e-03,
         -2.38701105e-02, -1.28174946e-03,  2.74519585e-02,
          8.18942860e-03],
        [ 1.58396028e-02, -1.56264789e-02, -8.79174471e-03,
         -4.13482413e-02,  4.69103567e-02,  4.63138893e-03,
         -2.38701105e-02, -1.28174946e-03,  2.74519585e-02,
          8.18942860e-03],
        [ 1.58396028e-02, -1.56264789e-02, -8.79174471e-03,
         -4.13482413e-02,  4.69103567e-02,  4.63138893e-03,
         -2.38701105e-02, -1.28174946e-03,  2.74519585e-02,
          8.18942860e-03],
        [ 1.58396028e-02, -1.56264789e-02, -8.79174471e-03,
         -4.13482413e-02,  4.69103567e-02,  4.63138893e-03,
         -2.38701105e-02, -1.28174946e-03,  2.74519585e-02,
          8.18942860e-03],
        [ 4.13138382e-02, -2.43962761e-02, -4.09400836e-02,
          1.49943270e-02, -2.18016747e-02, -1.74924135e-02,
         -2.35006567e-02,  2.08406709e-02, -4.087449

In [17]:
reshape_embedded = embedded_docs[0].reshape(-1,1)

In [18]:
model.predict(reshape_embedded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 315ms/step


array([[[ 0.04071001, -0.02962309,  0.04104323, -0.00145447,
          0.01920034,  0.01451508,  0.02813797,  0.04435859,
         -0.03546428,  0.04763044]],

       [[ 0.04071001, -0.02962309,  0.04104323, -0.00145447,
          0.01920034,  0.01451508,  0.02813797,  0.04435859,
         -0.03546428,  0.04763044]],

       [[ 0.04071001, -0.02962309,  0.04104323, -0.00145447,
          0.01920034,  0.01451508,  0.02813797,  0.04435859,
         -0.03546428,  0.04763044]],

       [[ 0.04071001, -0.02962309,  0.04104323, -0.00145447,
          0.01920034,  0.01451508,  0.02813797,  0.04435859,
         -0.03546428,  0.04763044]],

       [[-0.03628264,  0.02935051,  0.02062413,  0.00706133,
         -0.04891248, -0.03618628,  0.01136988, -0.03822089,
          0.02569095,  0.02030018]],

       [[ 0.02584745,  0.00789915, -0.04728546, -0.00168813,
          0.02058008,  0.04959858,  0.02674303,  0.04245622,
          0.04253619, -0.03194844]],

       [[-0.04442232, -0.03076485,  0.04